package fr.formation.inti.entities;


// Generated 28 avr. 2019 12:04:06 by Hibernate Tools 5.1.10.Final


import static javax.persistence.GenerationType.IDENTITY;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.GeneratedValue;



import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "urbanproject")
public class Comment implements java.io.Serializable {

	private Integer idComment;
	private AmbientPower ambientPower;
	private Signalement signalement;
	private UrbanPlanning urbanPlanning;
	private Users users;
	private Date date;
	private String text;

	public Comment() {
	}

	public Comment(Users users) {
		this.users = users;
	}

	public Comment(AmbientPower ambientPower, Signalement signalement, UrbanPlanning urbanPlanning, Users users,
			Date date, String text) {
		this.ambientPower = ambientPower;
		this.signalement = signalement;
		this.urbanPlanning = urbanPlanning;
		this.users = users;
		this.date = date;
		this.text = text;
	}

	@Id

	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_comment", unique = true, nullable = false)
	public Integer getIdComment() {
		return this.idComment;
	}

	public void setIdComment(Integer idComment) {
		this.idComment = idComment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ambientpowerid")
	public AmbientPower getAmbientPower() {
		return this.ambientPower;
	}

	public void setAmbientPower(AmbientPower ambientPower) {
		this.ambientPower = ambientPower;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "signalementid")
	public Signalement getSignalement() {
		return this.signalement;
	}

	public void setSignalement(Signalement signalement) {
		this.signalement = signalement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "urbanplanningid")
	public UrbanPlanning getUrbanPlanning() {
		return this.urbanPlanning;
	}

	public void setUrbanPlanning(UrbanPlanning urbanPlanning) {
		this.urbanPlanning = urbanPlanning;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usersidusers", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "text", length = 16777215)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}