package fr.formation.inti.entities;
// Generated 18 avr. 2019 16:14:00 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentId generated by hbm2java
 */
@Embeddable
public class CommentId implements java.io.Serializable {

	private int idComment;
	private int usersIdusers;
	private int signalementIdsignalement;
	private int ambientPowerIdambientPower;
	private int urbanPlanningIdplanningProposal;

	public CommentId() {
	}

	public CommentId(int idComment, int usersIdusers, int signalementIdsignalement, int ambientPowerIdambientPower,
			int urbanPlanningIdplanningProposal) {
		this.idComment = idComment;
		this.usersIdusers = usersIdusers;
		this.signalementIdsignalement = signalementIdsignalement;
		this.ambientPowerIdambientPower = ambientPowerIdambientPower;
		this.urbanPlanningIdplanningProposal = urbanPlanningIdplanningProposal;
	}

	@Column(name = "idComment", nullable = false)
	public int getIdComment() {
		return this.idComment;
	}

	public void setIdComment(int idComment) {
		this.idComment = idComment;
	}

	@Column(name = "users_idusers", nullable = false)
	public int getUsersIdusers() {
		return this.usersIdusers;
	}

	public void setUsersIdusers(int usersIdusers) {
		this.usersIdusers = usersIdusers;
	}

	@Column(name = "signalement_idsignalement", nullable = false)
	public int getSignalementIdsignalement() {
		return this.signalementIdsignalement;
	}

	public void setSignalementIdsignalement(int signalementIdsignalement) {
		this.signalementIdsignalement = signalementIdsignalement;
	}

	@Column(name = "ambient_power_idambient_power", nullable = false)
	public int getAmbientPowerIdambientPower() {
		return this.ambientPowerIdambientPower;
	}

	public void setAmbientPowerIdambientPower(int ambientPowerIdambientPower) {
		this.ambientPowerIdambientPower = ambientPowerIdambientPower;
	}

	@Column(name = "urban_planning_idplanning_proposal", nullable = false)
	public int getUrbanPlanningIdplanningProposal() {
		return this.urbanPlanningIdplanningProposal;
	}

	public void setUrbanPlanningIdplanningProposal(int urbanPlanningIdplanningProposal) {
		this.urbanPlanningIdplanningProposal = urbanPlanningIdplanningProposal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentId))
			return false;
		CommentId castOther = (CommentId) other;

		return (this.getIdComment() == castOther.getIdComment())
				&& (this.getUsersIdusers() == castOther.getUsersIdusers())
				&& (this.getSignalementIdsignalement() == castOther.getSignalementIdsignalement())
				&& (this.getAmbientPowerIdambientPower() == castOther.getAmbientPowerIdambientPower())
				&& (this.getUrbanPlanningIdplanningProposal() == castOther.getUrbanPlanningIdplanningProposal());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdComment();
		result = 37 * result + this.getUsersIdusers();
		result = 37 * result + this.getSignalementIdsignalement();
		result = 37 * result + this.getAmbientPowerIdambientPower();
		result = 37 * result + this.getUrbanPlanningIdplanningProposal();
		return result;
	}

}
