package fr.formation.inti.entities;
<<<<<<< HEAD
// Generated 25 avr. 2019 14:51:10 by Hibernate Tools 5.1.10.Final
=======
// Generated 25 avr. 2019 14:28:46 by Hibernate Tools 5.1.10.Final
>>>>>>> refs/heads/qtn

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
<<<<<<< HEAD
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
=======
>>>>>>> refs/heads/qtn
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "urbanproject")
public class Comment implements java.io.Serializable {

<<<<<<< HEAD
	private Integer idComment;
=======
	private int idComment;
>>>>>>> refs/heads/qtn
	private AmbientPower ambientPower;
	private Signalement signalement;
	private UrbanPlanning urbanPlanning;
	private Users users;
	private Date date;
	private String text;

	public Comment() {
	}

<<<<<<< HEAD
	public Comment(Users users) {
=======
	public Comment(int idComment, Users users) {
		this.idComment = idComment;
>>>>>>> refs/heads/qtn
		this.users = users;
	}

<<<<<<< HEAD
	public Comment(AmbientPower ambientPower, Signalement signalement, UrbanPlanning urbanPlanning, Users users,
			Date date, String text) {
=======
	public Comment(int idComment, AmbientPower ambientPower, Signalement signalement, UrbanPlanning urbanPlanning,
			Users users, Date date, String text) {
		this.idComment = idComment;
>>>>>>> refs/heads/qtn
		this.ambientPower = ambientPower;
		this.signalement = signalement;
		this.urbanPlanning = urbanPlanning;
		this.users = users;
		this.date = date;
		this.text = text;
	}

	@Id
<<<<<<< HEAD
	@GeneratedValue(strategy = IDENTITY)
=======
>>>>>>> refs/heads/qtn

	@Column(name = "idComment", unique = true, nullable = false)
<<<<<<< HEAD
	public Integer getIdComment() {
=======
	public int getIdComment() {
>>>>>>> refs/heads/qtn
		return this.idComment;
	}

<<<<<<< HEAD
	public void setIdComment(Integer idComment) {
=======
	public void setIdComment(int idComment) {
>>>>>>> refs/heads/qtn
		this.idComment = idComment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ambientpowerIdambientpower")
	public AmbientPower getAmbientPower() {
		return this.ambientPower;
	}

	public void setAmbientPower(AmbientPower ambientPower) {
		this.ambientPower = ambientPower;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "signalementIdsignalement")
	public Signalement getSignalement() {
		return this.signalement;
	}

	public void setSignalement(Signalement signalement) {
		this.signalement = signalement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "urbanplanningIdplanningproposal")
	public UrbanPlanning getUrbanPlanning() {
		return this.urbanPlanning;
	}

	public void setUrbanPlanning(UrbanPlanning urbanPlanning) {
		this.urbanPlanning = urbanPlanning;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usersIdusers", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "text", length = 16777215)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
