package fr.formation.inti.entities;
// Generated 25 avr. 2019 14:28:46 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Signalement generated by hbm2java
 */
@Entity
@Table(name = "signalement", catalog = "urbanproject")
public class Signalement implements java.io.Serializable {

	private Integer idsignalement;
	private String latitude;
	private String longitude;
	private Date datecreation;
	private String titre;
	private String descriptif;
	private String photopath;
	private String state;
	private String priority;
	private String category;
	private Integer compteurpopularite;
	private Integer compteurconstat;
	private String ref;
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Signalement() {
	}

	public Signalement(String latitude, String longitude, Date datecreation, String titre, String descriptif,
			String photopath, String category) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.datecreation = datecreation;
		this.titre = titre;
		this.descriptif = descriptif;
		this.photopath = photopath;
		this.category = category;
	}

	public Signalement(String latitude, String longitude, Date datecreation, String titre, String descriptif,
			String photopath, String state, String priority, String category, Integer compteurpopularite,
			Integer compteurconstat, String ref, Set<Comment> comments) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.datecreation = datecreation;
		this.titre = titre;
		this.descriptif = descriptif;
		this.photopath = photopath;
		this.state = state;
		this.priority = priority;
		this.category = category;
		this.compteurpopularite = compteurpopularite;
		this.compteurconstat = compteurconstat;
		this.ref = ref;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsignalement", unique = true, nullable = false)
	public Integer getIdsignalement() {
		return this.idsignalement;
	}

	public void setIdsignalement(Integer idsignalement) {
		this.idsignalement = idsignalement;
	}

	@Column(name = "latitude", nullable = false, length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datecreation", nullable = false, length = 10)
	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "titre", nullable = false)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "descriptif", nullable = false, length = 16777215)
	public String getDescriptif() {
		return this.descriptif;
	}

	public void setDescriptif(String descriptif) {
		this.descriptif = descriptif;
	}

	@Column(name = "photopath", nullable = false)
	public String getPhotopath() {
		return this.photopath;
	}

	public void setPhotopath(String photopath) {
		this.photopath = photopath;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "priority", length = 45)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "category", nullable = false, length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "compteurpopularite")
	public Integer getCompteurpopularite() {
		return this.compteurpopularite;
	}

	public void setCompteurpopularite(Integer compteurpopularite) {
		this.compteurpopularite = compteurpopularite;
	}

	@Column(name = "compteurconstat")
	public Integer getCompteurconstat() {
		return this.compteurconstat;
	}

	public void setCompteurconstat(Integer compteurconstat) {
		this.compteurconstat = compteurconstat;
	}

	@Column(name = "ref", length = 45)
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "signalement")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
