package fr.formation.inti.entities;
// Generated 24 avr. 2019 15:57:26 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpringSessionAttributes generated by hbm2java
 */
@Entity
@Table(name = "spring_session_attributes", catalog = "urbanproject")
public class SpringSessionAttributes implements java.io.Serializable {

	private SpringSessionAttributesId id;
	private SpringSession springSession;
	private byte[] attributeBytes;

	public SpringSessionAttributes() {
	}

	public SpringSessionAttributes(SpringSessionAttributesId id, SpringSession springSession, byte[] attributeBytes) {
		this.id = id;
		this.springSession = springSession;
		this.attributeBytes = attributeBytes;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sessionPrimaryId", column = @Column(name = "SESSION_PRIMARY_ID", nullable = false, length = 36)),
			@AttributeOverride(name = "attributeName", column = @Column(name = "ATTRIBUTE_NAME", nullable = false, length = 200)) })
	public SpringSessionAttributesId getId() {
		return this.id;
	}

	public void setId(SpringSessionAttributesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SESSION_PRIMARY_ID", nullable = false, insertable = false, updatable = false)
	public SpringSession getSpringSession() {
		return this.springSession;
	}

	public void setSpringSession(SpringSession springSession) {
		this.springSession = springSession;
	}

	@Column(name = "ATTRIBUTE_BYTES", nullable = false)
	public byte[] getAttributeBytes() {
		return this.attributeBytes;
	}

	public void setAttributeBytes(byte[] attributeBytes) {
		this.attributeBytes = attributeBytes;
	}

}
