package fr.formation.inti.entities;
// Generated 18 avr. 2019 16:14:00 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UrbanPlanning generated by hbm2java
 */
@Entity
@Table(name = "urban_planning", catalog = "urbanproject")
public class UrbanPlanning implements java.io.Serializable {

	private int idplanningProposal;
	private String latitude;
	private String longitude;
	private Date dateCreation;
	private byte temporalite;
	private Integer votePos;
	private Integer voteNeg;
	private String titre;
	private String descriptif;
	private String photoPath;
	private Set<Comment> comments = new HashSet<Comment>(0);

	public UrbanPlanning() {
	}

	public UrbanPlanning(int idplanningProposal, String latitude, String longitude, Date dateCreation, byte temporalite,
			String titre, String descriptif) {
		this.idplanningProposal = idplanningProposal;
		this.latitude = latitude;
		this.longitude = longitude;
		this.dateCreation = dateCreation;
		this.temporalite = temporalite;
		this.titre = titre;
		this.descriptif = descriptif;
	}

	public UrbanPlanning(int idplanningProposal, String latitude, String longitude, Date dateCreation, byte temporalite,
			Integer votePos, Integer voteNeg, String titre, String descriptif, String photoPath,
			Set<Comment> comments) {
		this.idplanningProposal = idplanningProposal;
		this.latitude = latitude;
		this.longitude = longitude;
		this.dateCreation = dateCreation;
		this.temporalite = temporalite;
		this.votePos = votePos;
		this.voteNeg = voteNeg;
		this.titre = titre;
		this.descriptif = descriptif;
		this.photoPath = photoPath;
		this.comments = comments;
	}

	@Id

	@Column(name = "idplanning_proposal", unique = true, nullable = false)
	public int getIdplanningProposal() {
		return this.idplanningProposal;
	}

	public void setIdplanningProposal(int idplanningProposal) {
		this.idplanningProposal = idplanningProposal;
	}

	@Column(name = "latitude", nullable = false, length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", nullable = false, length = 10)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "temporalite", nullable = false)
	public byte getTemporalite() {
		return this.temporalite;
	}

	public void setTemporalite(byte temporalite) {
		this.temporalite = temporalite;
	}

	@Column(name = "vote_pos")
	public Integer getVotePos() {
		return this.votePos;
	}

	public void setVotePos(Integer votePos) {
		this.votePos = votePos;
	}

	@Column(name = "vote_neg")
	public Integer getVoteNeg() {
		return this.voteNeg;
	}

	public void setVoteNeg(Integer voteNeg) {
		this.voteNeg = voteNeg;
	}

	@Column(name = "titre", nullable = false)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "descriptif", nullable = false, length = 16777215)
	public String getDescriptif() {
		return this.descriptif;
	}

	public void setDescriptif(String descriptif) {
		this.descriptif = descriptif;
	}

	@Column(name = "photo_path")
	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "urbanPlanning")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
