package fr.formation.inti.entities;
// Generated 25 avr. 2019 14:28:46 by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "urbanproject", uniqueConstraints = @UniqueConstraint(columnNames = "mail"))
public class Users implements java.io.Serializable {

	private Integer idusers;
	@Email
	private String mail;
	@NotNull
    @Size(min=1, message="Veuillez indiquer un pseudo")
	private String pseudo;
	@NotNull
    @Size(min=8, message="Votre mot de passe doit contenir au moins 8 caractères")
	private String password;
	@NotNull
	@Size(min=1, message="Veuillez indiquer un numéro et une rue")
	private String street;
	@NotNull
	@Size(min=1, message="Veuillez indiquer une ville")
	private String city;
	@NotNull(message="Veuillez indiquer un code postal")
	private Integer zipcode;
	@NotNull
	@Size(min=1, message="Veuillez indiquer un pays")
	private String country;
	@NotNull(message = "Veuillez indiquer une date de naissance")
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date birthdate;
	@NotNull
	@Size(min=1, message="Veuillez indiquer un prénom")
	private String firstname;
	@NotNull
	@Size(min=1, message="Veuillez indiquer un nom de famille")
	private String lastname;
	@JsonIgnore
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Users() {
	}

	public Users(String mail, String password) {
		this.mail = mail;
		this.password = password;
	}

	public Users(String mail, String pseudo, String password, String street, String city, Integer zipcode,
			String country, Date birthdate, String firstname, String lastname, Set<Comment> comments) {
		this.mail = mail;
		this.pseudo = pseudo;
		this.password = password;
		this.street = street;
		this.city = city;
		this.zipcode = zipcode;
		this.country = country;
		this.birthdate = birthdate;
		this.firstname = firstname;
		this.lastname = lastname;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idusers", unique = true, nullable = false)
	public Integer getIdusers() {
		return this.idusers;
	}

	public void setIdusers(Integer idusers) {
		this.idusers = idusers;
	}

	@Column(name = "mail", unique = true, nullable = false, length = 45)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "pseudo", length = 45)
	public String getPseudo() {
		return this.pseudo;
	}

	public void setPseudo(String pseudo) {
		this.pseudo = pseudo;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zipcode")
	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 10)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
